### ISSUE TITLE
window 10  ImportError: cannot import name 'AudioStreamTrack' from 'aiortc' 

### ISSUE THREAD

**Issue by aakashaarya** [skglobal-jsc/kivyrtc#2]
Traceback (most recent call last):
   File "C:\Users\aakas\Desktop\kivymd\lib\kivyrtc-master\main.py", line 6, in <module>
     from kivyrtc.app import KivyRTCApp
   File "C:\Users\aakas\Desktop\kivymd\lib\kivyrtc-master\kivyrtc\app.py", line 21, in <module>
     from .mediastreams import VideoImageTrack, AudioTrack
   File "C:\Users\aakas\Desktop\kivymd\lib\kivyrtc-master\kivyrtc\mediastreams.py", line 10, in <module>
     from aiortc import AudioStreamTrack
 ImportError: cannot import name 'AudioStreamTrack' from 'aiortc' (C:\Users\aakas\AppData\Local\Programs\Python\Python39\lib\site-packages\aiortc\__init__.py)

**Comment by ItaruTran** [comment]
`AudioStreamTrack` has been removed in the latest version.
You should use [MediaStreamTrack](https://aiortc.readthedocs.io/en/latest/api.html#media) instead
